project:
  resources:
    - "spring-*/**"
  type: website
  output-dir: docs

website:
  title: "AEM 7010"
  description: "AEM 7010: Doing Applied Economics Research. Practical Skills."
  favicon: images/favicon.ico
  navbar:
    background: light
    logo: images/cornell_seal_simple_web_b31b1b.svg
    title: "<span class='nav-title-code'>AEM 7010</span><span class='nav-title-subtitle'>Doing Applied Economics Research: Practical Skills</span>"
    search: true
    right:
      - text: "Home"
        href: index.qmd
  page-footer:
    left: "Prof. Ariel Ortiz-Bobea, Cornell Dyson School"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - cosmo
      - cornell.scss
    toc: true
    toc-location: right
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    code-block-bg: true
    link-external-newwindow: true
    grid:
      sidebar-width: 220px
      body-width: 760px
      margin-width: 220px
      gutter-width: 1.5rem
